# Dependencies
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".travis.yml",  "node_modules", "scss", "bower_components", "grunt"]
highlighter: true
markdown: kramdown

# Permalinks
permalink: /:categories/:year/:month/:day/:title

# Setup
title : Kevin Quillen
tagline: Still coding. Still rocking. Still ranting.
description: Still coding. Still rocking. Still ranting.
url: http://kevinquillen.com
author :
  name : Kevin Quillen
  email : kevin@inclind.com
  drupal : https://drupal.org/user/317279
  github : https://github.com/kevinquillen
  twitter : https://twitter.com/kevinquillen
  linkedin : http://www.linkedin.com/kevinquillen
  tagline: still coding. still laughing. still rocking. still ranting.

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:  /assets/images/code-1.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/kevinquillen
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/kevinquillen
    desc:	Fork me on github

  - icon:	cog
    url:	https://drupal.org/user/317279
    desc:	My Drupal.org Profile

  - icon:	linkedin
    url:	http://www.linkedin.com/kevinquillen
    desc:	Add me on LinkedIn

  - icon:	feed
    url:	http://kevinquillen.com/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	Kevin Quillen
  url:		http://kevinquillen.com
  type_title:	All rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

production_url : http://kevinquillen.com
rss_path: rss.xml
